# Exercise 3.1

In [1]:
import numpy as np

1) Create 4x4 numpy array ranging from 0 to 16. Name it `my_arr`

In [2]:
my_arr = np.arange(16).reshape(4, 4)

In [3]:
my_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

2) Extract the diagonal of this array. <br>
**Hint**: use `np.eye()` and masking

In [4]:
my_arr[np.eye(4) > 0]

array([ 0,  5, 10, 15])

3) Make all the elements in `my_arr`, except the diagonal, zero.

In [5]:
my_arr = np.eye(4) * my_arr

In [6]:
my_arr

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 15.]])

4) Using a numpy function, find the index of the non-zero values in the given list. <br>
**Hint**: Look into `np.nonzero()`

In [7]:
np.nonzero(my_arr)

(array([1, 2, 3]), array([1, 2, 3]))

5) Change `my list` to a numpy array and find the non-zero element of the resulting array.

In [8]:
my_list = [1, 2, 3, 4, 5]

In [9]:
my_arr = np.array(my_list)

In [10]:
my_arr

array([1, 2, 3, 4, 5])

In [11]:
np.nonzero(my_arr)

(array([0, 1, 2, 3, 4]),)

6) Using the numpy function `np.where()` find the index of the non-zero element of the array from previous exercise.

In [12]:
np.where(my_arr != 0)

(array([0, 1, 2, 3, 4]),)

7) Given a 1D array, negate all elements which are between 3 and 8, in place.

In [13]:
x = np.arange(11)

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
x[(8 > x) & (x > 3)] = x[(8 > x) & (x > 3)] * -1

In [16]:
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

8) Create a random 1D numpy array of size 10 and with integer values. Name it `int_arr`.

In [17]:
int_arr = np.random.randint(0, 20, size=(10,))

9) Sort this array in descending order. <br>
**Hint**: Look into `np.sort()`

In [18]:
my_arr = np.arange(9).reshape(3, 3)

In [19]:
my_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
my_arr[0:-1, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
np.sort(int_arr)[::-1]

array([15, 15, 15, 11, 11, 11, 10,  8,  6,  0])

10) Two arrays are given below, `a_arr` and `b_arr`. 
- Sort `a_arr` in descending
- Sort `b_arr` with the same order of elements as `a_arr`

**Hint**: Look into `np.argsort()`

In [22]:
a_arr = np.array([2, 1, 3])
b_arr = np.array([5, 10, 15])

In [23]:
np.sort(a_arr)[::-1]

array([3, 2, 1])

In [24]:
b_arr[np.argsort(a_arr)[::-1]]

array([15,  5, 10])

11) Sort the following array by the 3rd column?

In [25]:
my_arr = np.random.randint(0, 20, size=(7, 10))
my_arr

array([[10,  0, 10, 12, 12, 11, 10, 13, 17,  4],
       [ 5,  8,  0,  9, 12,  0,  5,  8,  2, 16],
       [ 3, 14, 16, 17, 18,  5, 17, 11,  2,  9],
       [18, 18, 16,  3,  4, 15,  4,  0, 11, 16],
       [ 5, 18, 16,  9,  7, 17,  7,  0, 14, 13],
       [ 8,  5, 16,  9, 16,  4, 11, 12,  4, 13],
       [ 1,  8,  4,  4,  4, 14, 18, 19,  5,  2]])

In [26]:
my_arr[np.argsort(my_arr[:, 2]), :]

array([[ 5,  8,  0,  9, 12,  0,  5,  8,  2, 16],
       [ 1,  8,  4,  4,  4, 14, 18, 19,  5,  2],
       [10,  0, 10, 12, 12, 11, 10, 13, 17,  4],
       [ 3, 14, 16, 17, 18,  5, 17, 11,  2,  9],
       [18, 18, 16,  3,  4, 15,  4,  0, 11, 16],
       [ 5, 18, 16,  9,  7, 17,  7,  0, 14, 13],
       [ 8,  5, 16,  9, 16,  4, 11, 12,  4, 13]])

12) For the given array:
- subtract the mean of each column from the column, and then
- divide each column by the standard deviation of the column

In [34]:
my_arr = np.random.randn(20, 3)
my_arr

array([[-0.0882875 ,  1.81128162,  0.44473321],
       [-0.40874148, -0.31666451,  0.5007857 ],
       [ 0.03295327,  0.46998078,  1.10503153],
       [ 0.47375459,  1.17916103, -0.34425075],
       [ 0.29870394,  0.30669196,  0.83647576],
       [ 1.00648159,  1.17675585, -0.84517285],
       [-0.92656725, -0.96781415, -0.40927907],
       [-0.65699184, -0.54464054,  0.23774575],
       [ 0.06652798,  0.74953904,  0.03170453],
       [ 1.62231894,  0.72284327,  1.90466117],
       [-0.47789231, -0.04477025, -1.30987136],
       [ 0.50096233, -0.30494405,  0.78109349],
       [-0.60112264, -0.04166354, -0.57039642],
       [ 1.31726326, -0.39801226,  1.39864055],
       [ 2.48546343,  0.2584317 ,  0.1167121 ],
       [-0.57698366, -2.14218436,  0.89591664],
       [-0.77838286, -0.33430093,  0.03133534],
       [-0.78938167, -0.00556876, -0.51822581],
       [ 2.10527738,  0.50487184,  1.06686096],
       [ 0.75290961,  0.77305693,  0.7618042 ]])

In [35]:
my_arr.mean(axis=0)

array([0.26791326, 0.14260253, 0.30581523])

In [36]:
my_arr.std(axis=0)

array([0.98254683, 0.84431096, 0.79360829])

In [37]:
my_arr = (my_arr - my_arr.mean(axis=0)) / my_arr.std(axis=0)

In [38]:
my_arr.mean(axis=0)

array([-5.27355937e-17, -8.32667268e-17,  0.00000000e+00])

In [39]:
my_arr.std(axis=0)

array([1., 1., 1.])