# Day 3 warm-up exercises

---

1) Write a function that raises its input to the power of 2. Call the function `square`.

In [1]:
def square(x):
    y = x ** 2
    return y

In [2]:
square(5)

25

2) Write a function that takes the square root of the input. Call it `sqrt`.

In [3]:
def sqrt(x):
    y = x ** .5
    return y

In [4]:
sqrt(25)

5.0

3) Given a number, write an if-statement that raises the number to the power of 2 if it is bigger than or equal to 1 and takes the square root otherwise.

In [14]:
a = 5

In [15]:
if a >= 1:
    print(square(a))
elif a < 0:
    print("Sorry, not supported!")
else:
    print(sqrt(a))

25


4) Create a Numpy array ranging from 0 to 9, and with a shape of (3, 3).

In [16]:
import numpy as np

In [17]:
my_arr = np.arange(9).reshape(3, 3)

In [18]:
my_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5) multiply the 3rd column of the array by 2.

In [22]:
my_arr[:, 2] = my_arr[:, 2] * 2

In [23]:
my_arr

array([[ 0,  1,  4],
       [ 3,  4, 10],
       [ 6,  7, 16]])

In [24]:
my_arr[:, 2] = my_arr[:, 2] / 2

In [25]:
my_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6) Raise the last row of the array to the power of 5.

In [27]:
my_arr[-1, :] ** 5

array([ 7776, 16807, 32768])

---