# Exercise 2.3

---

1) Import the numpy package under the name `np`.

In [1]:
import numpy as np

## Creating numpy arrays

Numpy provides several ways to create numpy arrays. Use `np.zeros()`, `np.ones()`, `np.arange()`, `np.random.randn()`, `np.linspace()` to create numpy arrays in the following tasks.

2) Create a vector with values ranging from 0 to 10 (up to).

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3) Create a vector ranging from 5 to 10 (up to).

In [3]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

4) Create a vector of zeros with 10 elements

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

5) Create a vector of ones with 10 elements

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

6) Create a vector ranging from 0 to 10, where the difference between each value is .1, instead of 1.

In [6]:
np.arange(0, 10, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

7) Create a vector starting from 10.1, ending on 12, with 20 elements.

In [7]:
np.linspace(10.1, 12, 20)

array([10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. , 11.1,
       11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ])

8) Create a 3x3 numpy array with random values.

In [8]:
np.random.randn(3, 3)

array([[-0.17844731,  0.37102307,  1.82070945],
       [-0.58449712, -0.42362495,  0.65875347],
       [-0.31740413,  2.03557528, -0.71111327]])

## Data Inspection

Before starting to work with any data, it's a good idea to get some insight about the data:
- How many dimensions does it have
- How many elements does it have in each dimensions (mainly number of rows, columns)

9) How many dimension does the following numpy array have?

In [9]:
my_arr = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
my_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
my_arr.ndim

2

10) How many elements does it have in each dimension (i.e., what is the shape of it)?

In [13]:
my_arr.shape

(2, 3)

11) What is the data type of the elements of `my_arr`?

In [14]:
my_arr.dtype

dtype('int64')

12) Create a 3x3 numpy array ranging from 0 to 9 (up  to). Name this array `my_arr`.

In [15]:
my_arr = np.arange(9).reshape(3, 3)

In [16]:
my_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<br>
Sometimes, we might need to create an array based on the dimensions of another.

13) Create a numpy array of zeros same size as `my_arr`.

In [17]:
np.zeros_like(my_arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

14) Resize `my_arr` to become a vector (only with one dimension).

In [18]:
my_arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Aggregation and transformation

16) Find the following information for the given array
- minimum value
- maximum value
- mean
- std
- row and column with minimum values
- row and column with maximum values
- mean of each column (though rows)
- mean of each row
- std of each row
- std of each column

In [19]:
my_val = [[1, 2, 3, 4], [2, 3, 4, 5]]
my_arr = np.array(my_val)

In [20]:
my_arr.std(axis=1)

array([1.11803399, 1.11803399])

For the following two numpy arrays, perform the following element-wise operations using numpy functions.

In [21]:
a_arr = np.arange(10, 51, 5)
b_arr = np.arange(1, 10)

In [22]:
a_arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [23]:
b_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

17) Divide `a_arr` by `b_arr`.

In [24]:
np.divide(a_arr, b_arr)

array([10.        ,  7.5       ,  6.66666667,  6.25      ,  6.        ,
        5.83333333,  5.71428571,  5.625     ,  5.55555556])

18) What is the remainder of previous operation?

In [25]:
np.remainder(a_arr, b_arr)

array([0, 1, 2, 1, 0, 5, 5, 5, 5])

19) multiply the 3rd column of th following array by 2

In [26]:
my_arr = np.random.randint(0, 10, size=(3, 3))
my_arr

array([[7, 9, 4],
       [4, 7, 3],
       [5, 7, 1]])

In [28]:
my_arr[:, 2] = my_arr[:, 2] * 2

In [29]:
my_arr

array([[7, 9, 8],
       [4, 7, 6],
       [5, 7, 2]])

20) Raise the last row of the following array to the power of 5.

In [37]:
my_arr = np.random.randint(0, 10, size=(5, 5))

In [38]:
my_arr

array([[3, 8, 1, 1, 6],
       [3, 2, 2, 8, 4],
       [6, 2, 1, 4, 4],
       [3, 6, 8, 2, 6],
       [5, 5, 1, 1, 3]])

In [39]:
my_arr[-1, :] = my_arr[-1, :] ** 5

In [40]:
my_arr

array([[   3,    8,    1,    1,    6],
       [   3,    2,    2,    8,    4],
       [   6,    2,    1,    4,    4],
       [   3,    6,    8,    2,    6],
       [3125, 3125,    1,    1,  243]])

---